### ISSUE TITLE
Fix menubar

### ISSUE THREAD

**Issue by nitantchhajed** [nitantchhajed/op-stack-bridge#2]
Only Keep Bridge and account tab. add route to bridge button

![image](https://github.com/nitantchhajed/op-stack-bridge/assets/96972634/1b845d0d-0494-4b80-83f8-7a318b6deca4)

**Comment by mayankmotiyani** [comment]
we are removing bridge and account from Navbar.. and will manage account history(view deposits and view withdrawals) on connect and disconnect button ..

**Comment by nitantchhajed** [comment]
nice
