### ISSUE TITLE
how to configure providers

### ISSUE THREAD

**Issue by norfolkpine** [nitantchhajed/op-stack-bridge#7]
Hi, 

Appreciate the code. How do I configure my own chain as a provider?

Thanks

**Comment by nitantchhajed** [comment]
add `REACT_APP_L2_RPC_URL` in your .env file

**Comment by norfolkpine** [comment]
cool, got it to work.
I have another error where the server is crashing, I believe it relates to the number of watchers as I had to increase the count on my system. 
Have you experienced this?

**Comment by nitantchhajed** [comment]
No i did not experience any of these

**Comment by norfolkpine** [comment]
hmm, wierd. I will try the latest commit.

If I send to 0x29...79c961 on Goerli to bridge my tokens onto the layer 2, which address do I send to on the layer 2 to bridge them back to layer 2?

Is it 0x29...79c961 on both layer 1 and layer 2?

My eth isnt bridging back for some reason

**Comment by norfolkpine** [comment]
> hmm, wierd. I will try the latest commit.
> 
> If I send to 0x29...79c961 on Goerli to bridge my tokens onto the layer 2, which address do I send to on the layer 2 to bridge them back to layer 2?
> 
> Is it 0x29...79c961 on both layer 1 and layer 2?
> 
> My eth isnt bridging back for some reason
For anyone whose looking:

OVM_L2ToL1MessagePasser: '0x4200000000000000000000000000000000000000',
    OVM_DeployerWhitelist: '0x4200000000000000000000000000000000000002',
    L2CrossDomainMessenger: '0x4200000000000000000000000000000000000007',
    OVM_GasPriceOracle: '0x420000000000000000000000000000000000000F',
    **L2StandardBridge: '0x4200000000000000000000000000000000000010',**
    OVM_SequencerFeeVault: '0x4200000000000000000000000000000000000011',
    L2StandardTokenFactory: '0x4200000000000000000000000000000000000012',
    OVM_L1BlockNumber: '0x4200000000000000000000000000000000000013',
    OVM_ETH: '0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000',
    WETH9: '0x4200000000000000000000000000000000000006',

**Comment by norfolkpine** [comment]
For some reason its still not bridging back. I've traced the coins to 0x4200000000000000000000000000000000000016
Then no action is being taken on the Goerli side

**Comment by nitantchhajed** [comment]
> For some reason its still not bridging back. I've traced the coins to 0x4200000000000000000000000000000000000016 Then no action is being taken on the Goerli side

did you prove the transaction ??

**Comment by nitantchhajed** [comment]
click on view withdrawals and prove your withdrawal and then you can claim it after challenge period ends. : )

![image](https://github.com/nitantchhajed/op-stack-bridge/assets/96972634/fb0305e5-9784-48bf-8ab2-d948ab3cbd39)
