### ISSUE TITLE
UI support for Sepolia

### ISSUE THREAD

**Issue by iTranscend** [nitantchhajed/op-stack-bridge#9]
Currently, Sepolia is reported as an unsupported network in the UI but bridging still works fine.

It would be great if the Sepolia testnet were added to the UI since Goerli's end of life is January 2024

**Comment by nitantchhajed** [comment]
hey @iTranscend  I just released the new version of this bridge, which supports sepolia.

**Comment by iTranscend** [comment]
Nice 💪 

GG
